#! /bin/bash

#Allow Exclamation points to be used in commands by turning off the history
set +H

FS_SIZE=50G
MAX_FILE_LENGTH=10
FILE_LENGTH_IF_ZERO=20
MAX_FILES_WITH_NONLETTERS=1024
MAX_FOLDERS_WITH_NONLETTERS=1024

MAX_FOLDER_COUNT=100000
MAX_FILE_COUNT=10000000

echo "Warning: This tries to create GB worth of files in /tmp."
read a

DateStamp=$(date +%s)
mkdir /tmp/kiocopy
mkdir /tmp/kiocopy/$DateStamp
mkdir /tmp/kiocopy/$DateStamp/folder_src
mkdir /tmp/kiocopy/$DateStamp/folder_dest

truncate --size $FS_SIZE /tmp/kiocopy/$DateStamp/fsimg_src
truncate --size $FS_SIZE /tmp/kiocopy/$DateStamp/fsimg_dest
mkfs.ext4  /tmp/kiocopy/$DateStamp/fsimg_src
mkfs.btrfs /tmp/kiocopy/$DateStamp/fsimg_dest

sudo mount -o loop  /tmp/kiocopy/$DateStamp/fsimg_src /tmp/kiocopy/$DateStamp/folder_src
if [[ $? != 0 ]]
then
  echo "EXT4 FS failed to mount"
  exit
fi
sudo mount -o loop  /tmp/kiocopy/$DateStamp/fsimg_dest /tmp/kiocopy/$DateStamp/folder_dest
if [[ $? != 0 ]]
then
  echo "BTRFS FS failed to mount"
  exit
fi

sudo chown $UID /tmp/kiocopy/$DateStamp/folder_src
sudo chown $UID /tmp/kiocopy/$DateStamp/folder_dest

export QT_LOGGING_RULES=kf5.kio.*=true


#Generate random char of type
#0=lowercase
#1=uppercase
#2=number
#4=silly chars that break scripts and parsing
#5=Odd ascii/unicode points
function CreateRandomChar {
  CharType=$1
  #LowercaseChars=(a b c d e f g h i j k l m n o p q r s t u v w x y z â ä à å ç ê ë è ï î ì æ)
  #UppercaseChars=(A B C D E F G H I J K L M N O P Q R S T U V W X W Z Ä Å Ä É Æ)
  #WhitespaceChars=(" ")
  #NumberChars=(0 1 2 3 4 5 6 7 8 9)
  #SillyChars=("\\" "\"" ";" ":" "&" "#" "*" "@" "~" "{" "}" "(" ")" "'" "?" "<" ">" " " $'\t' "." "," "-")
  #OddChars=("©" "¾" "📋" "🐧" "䉎" "𖡒" "ԑ" "ĳ" "®" "╚")
  LowercaseChars=(a b c)
  UppercaseChars=(A B C)
  NumberChars=(1 2 3)
  WhitespaceChars=(" ")
  SillyChars=("\\" "\"" ";" ":" "&" "#" "*" "@" "~" "{" "}" "(" ")" "'" "?" "<" ">" " " $'\t' "." "," "-")
  OddChars=("©" "¾" "📋")
  if [[ $CharType == 0 ]]
  then
    MaxElement=${#LowercaseChars[@]}
    ChooseElement=$(( $RANDOM % $MaxElement ))
    ChooseChar=${LowercaseChars[$ChooseElement]}
  elif [[ $CharType == 1 ]]
  then
    MaxElement=${#UppercaseChars[@]}
    ChooseElement=$(( $RANDOM % $MaxElement ))
    ChooseChar=${UppercaseChars[$ChooseElement]}
  elif [[ $CharType == 2 ]]
  then
    MaxElement=${#NumberChars[@]}
    ChooseElement=$(( $RANDOM % $MaxElement ))
    ChooseChar=${NumberChars[$ChooseElement]}
  elif [[ $CharType == 3 ]]
  then
    MaxElement=${#SillyChars[@]}
    ChooseElement=$(( $RANDOM % $MaxElement ))
    ChooseChar=${SillyChars[$ChooseElement]}
  elif [[ $CharType == 4 ]]
  then
    MaxElement=${#OddChars[@]}
    ChooseElement=$(( $RANDOM % $MaxElement ))
    ChooseChar=${OddChars[$ChooseElement]}
  fi

  if [[ ! -z $2 ]]
  then
    printf -v "$2" '%s' "$ChooseChar"
  else
    echo "$ChooseChar"
  fi
}


#Don't flood with too many unreadable symbols, will make reading logs hard for devs, max it out
OddCharFolderCount=0
OddCharFileCount=0

#First argument if if should be a file name or folder name
#Second is argument with the name
function CreateObjectName {
  IsFile=$1
  if [[ $IsFile != 0 && $IsFile != 1 ]]
  then
    IsFile=0
  fi

  RandomSeed=$RANDOM
  LengthHint=$(($RANDOM % $MAX_FILE_LENGTH))
  if [[ $LengthHint -eq 0 ]]
  then
    Length=$FILE_LENGTH_IF_ZERO
  else
    Length=$LengthHint
  fi

  NewName=""
  for (( CharItr=0 ; CharItr < $Length ; CharItr++ ))
  do
    if [[ $IsFile == 1 ]]
    then
      if [[ $OddCharFileCount < $MAX_FILES_WITH_NONLETTERS ]]
      then
        NameCharType=$(($RANDOM % 5))
      else
        NameCharType=$(($RANDOM % 3))
      fi
    else
      if [[ $OddCharFolderCount < $MAX_FOLDERS_WITH_NONLETTERS ]]
      then
        NameCharType=$(($RANDOM % 5))
      else
        NameCharType=$(($RANDOM % 3))
      fi
    fi
    CreateRandomChar $NameCharType NameChar
    NewName+=$NameChar
  done
  
  if [[ $IsFile == 1 ]]
  then
    ((OddCharFileCount++))
    ExtChar1Type=$(($RANDOM % 3))
    ExtChar2Type=$(($RANDOM % 3))
    ExtChar3Type=$(($RANDOM % 3))
    CreateRandomChar $ExtChar1Type ExtChar1
    CreateRandomChar $ExtChar2Type ExtChar2
    CreateRandomChar $ExtChar3Type ExtChar3
    NewName+="."
    NewName+=$ExtChar1
    NewName+=$ExtChar2
    NewName+=$ExtChar3
  else
    ((OddCharFolderCount++))
  fi

  if [[ ! -z $2 ]]
  then
    printf -v "$2" '%s' "$NewName"
  else
    echo "$NewName"
  fi
}

#This creates Folders, it randomly selects the index of a folder, grabs the name, creates a random folder name
#and creates the folder name, saving the full path to the array. this array of folders is used to create more folders
#since the full path is in the array, and the name gets added.
FolderList=()
FolderList+=("/")
function CreateFolder {
  FolderCount=${#FolderList[@]}
  DestFolderID=$(( $RANDOM % $FolderCount ))
  DestFolderName=${FolderList[$DestFolderID]}
  CreateObjectName 0 NewFolderName
  LastDestFolderName=${DestFolderName:$((${#DestFolderName} -1 )):1}
  if [[ $LastDestFolderName == "/" ]]
  then
    NewPath="$DestFolderName$NewFolderName"
  else
    NewPath="$DestFolderName/$NewFolderName"
  fi
  FolderList+=("$NewPath")
  
  mkdir "/tmp/kiocopy/$DateStamp/folder_src/$NewPath"
}


#This creates files, it randomly selects the index of a folder, grabs the name, creates a random file name
#and creates the file, saving the full path to an array
FileList=()
function CreateFile {
  FolderCount=${#FolderList[@]}
  DestFolderID=$(( $RANDOM % $FolderCount ))
  DestFolderName=${FolderList[$DestFolderID]}
  CreateObjectName 1 NewFileName
  if [[ $LastDestFolderName == "/" ]]
  then
    NewPath="$DestFolderName$NewFileName"
  else
    NewPath="$DestFolderName/$NewFileName"
  fi
  FileList+=("$NewPath")
  
  #TODO CREATE FILE
  #TODO Decide size
  echo $NewPath
}

#Create the Folder Tree
echo "Creating folder tree..."
for (( FolderItr=0 ; FolderItr < $MAX_FOLDER_COUNT ; FolderItr++ ))
do
  CreateFolder
done

#Create the files
echo "Creating files..."
for (( FileItr=0 ; FileItr < $MAX_FILE_COUNT ; FileItr++ ))
do
  CreateFile
done

#log folders
mkdir /tmp/kiocopy/$DateStamp/logs
for Folder in  "${FolderList[@]}"
do
  echo $Folder >> /tmp/kiocopy/$DateStamp/logs/FolderList.txt
done

#Log files
for File in  "${FileList[@]}"
do
  echo $File >> /tmp/kiocopy/$DateStamp/logs/FileList.txt
done




#The actual test for trying to copy the folders, along with post logging.

kioclient copy /tmp/kiocopy/$DateStamp/folder_src /tmp/kiocopy/$DateStamp/folder_dest &> /tmp/kiocopy/$DateStamp/logs/kioclient.log
echo "$?" >> /tmp/kiocopy/$DateStamp/report.log
diff -rq /tmp/kiocopy/$DateStamp/folder_src /tmp/kiocopy/$DateStamp/folder_dest > /tmp/kiocopy/$DateStamp/logs/folderdiff.txt
tree /tmp/kiocopy/$DateStamp/folder_src  > /tmp/kiocopy/$DateStamp/logs/src_tree.txt
tree /tmp/kiocopy/$DateStamp/folder_dest > /tmp/kiocopy/$DateStamp/logs/dest_tree.txt


umount /tmp/kiocopy/$DateStamp/fsimg_src
umount /tmp/kiocopy/$DateStamp/fsimg_dest
