#! /bin/bash
#    Copyright (c) 2012, 2013, 2014, 2015, 2016, 2017, 2018 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is (going to be) part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

set +H
###########################################################################################




#TODO, handle =, handle whitespace at starts of lines, mainarray

HandledFileCount=0
SeatBackendArrayElementOffset=5
for WSESSIONFILE in /home/nerdopolis/Desktop/rebeccablacklinux/rebeccablackos_files/usr/share/wsessions.d/*.desktop
do
  #read up to 16385 bytes from the config file, if it is 16385 bytes ignore it
  #The most accepted bytes is 16384, or 16KB, which is more than enough
  if [[ -f "$WSESSIONFILE" ]]
  then
    read -r -n 16385 -d $'\r' WSESSIONFILEDATA 2>/dev/null < "$WSESSIONFILE"
  else
    WriteToLog "$WSESSIONFILE is not a file"
    continue
  fi

  #If the file is too large
  if [[ ${#WSESSIONFILEDATA} == 16385 ]]
  then
    WriteToLog "$WSESSIONFILE is too large, and will be ignored"
    continue
  fi

  #Convert the file data to an array
  readarray -t WSESSIONFILEDATA <<< "$WSESSIONFILEDATA"

  #Build the initial array for the main keys
  WSESSIONFILEARRAY=""
  for Iterator in {000..012}
  do
    if [[ ! -z $WSESSIONFILEARRAY ]]
    then
      WSESSIONFILEARRAY+=$'\n'
    fi
    WSESSIONFILEARRAY+=${Iterator}"#"
  done
  WSESSIONFILEARRAY+=$'\r'
  readarray -t WSESSIONFILEARRAY <<< "$WSESSIONFILEARRAY"

  #Build the initial array for the NeedsFile list
  NeedsFileArray=()
  NeedsFileArray+=("$WSESSIONFILE")

  #Build the initial array for the backend support table
  SeatBackendArray=""
  for BACKEND in KMS WL FB
  do
    for Iterator in {000..004}
    do
      if [[ ! -z $SeatBackendArray ]]
      then
        SeatBackendArray+=$'\n'
      fi
      SeatBackendArray+=${Iterator}"#"${BACKEND}"#"
    done
  done
  readarray -t SeatBackendArray <<< "$SeatBackendArray"

  #Handle all the valid lines in the file
  ParseINISegment=0
  for WSESSIONLINE in "${WSESSIONFILEDATA[@]}"
  do
    if [[ $ParseINISegment == 1 && $WSESSIONLINE =~ ^[[:space:]]*"["  ]]
    then
      ParseINISegment=0
    fi
    if [[ $WSESSIONLINE == "[Desktop Entry]" ]]
    then
      ParseINISegment=1
      continue
    fi
    if [[ $ParseINISegment == 0 ]]
    then
      continue
    fi

    IFS="="
    WSESSIONLINE=($WSESSIONLINE)
    unset IFS

    #Set the NeedFile
    if [[ ${WSESSIONLINE[0]} == NeedsFile ]]
    then
      NeedsFileArray+=(${WSESSIONLINE[1]})
    fi

    #If the line is for a backend, determine what element to set on the backend array
    #Each backend has a number elements each, and are always in order KMS, WL, FB
    #The number of elements are fixed place for if it's supports the backend, arguments for the backend, if the backend supports seats, ect.
    if [[ ${WSESSIONLINE[0]} =~ [a-Z]*KMS[a-Z]* || ${WSESSIONLINE[0]} =~ [a-Z]*WL[a-Z]* || ${WSESSIONLINE[0]} =~ [a-Z]*FB[a-Z]* ]]
    then
      for BACKEND in KMS WL FB
      do
        SeatBackendArrayOffset=-1
        if [[ $BACKEND == KMS ]]
        then
          SeatBackendArrayMultiplicand=0
        elif [[ $BACKEND == WL ]]
        then
          SeatBackendArrayMultiplicand=1
          elif [[ $BACKEND == FB ]]
        then
          SeatBackendArrayMultiplicand=2
        fi


        if [[ ${WSESSIONLINE[0]} =~ CompositorSupports${BACKEND} ]]
        then
          SeatBackendArrayOffset=0
        fi
        if [[ ${WSESSIONLINE[0]} =~ Compositor${BACKEND}SeatAware ]]
        then
          SeatBackendArrayOffset=1
        fi
        if [[ ${WSESSIONLINE[0]} =~ Compositor${BACKEND}Arguments ]]
        then
          SeatBackendArrayOffset=2
        fi
        if [[ ${WSESSIONLINE[0]} =~ Compositor${BACKEND}SeatArgument ]]
        then
          SeatBackendArrayOffset=3
        fi

        if [[ $SeatBackendArrayOffset != -1 ]]
        then
          printf -v OffsetID "%03d" $SeatBackendArrayOffset
          BackendArrayChangeElement=$(( (SeatBackendArrayElementOffset * SeatBackendArrayMultiplicand) + SeatBackendArrayOffset ))
          if [[ ${SeatBackendArray[$BackendArrayChangeElement]} == "$OffsetID#${BACKEND}#" ]]
          then
            SeatBackendArray[$BackendArrayChangeElement]="$OffsetID#${BACKEND}#${WSESSIONLINE[1]}"
          fi
        fi
      done
    fi


  done



  #unset WSESSIONFILEDATA
  ((HandledFileCount++))
done
unset WSESSIONFILELIST

