#! /bin/bash
#    Copyright (c) 2012, 2013, 2014, 2015, 2016, 2017, 2018 nerdopolis (or n3rdopolis) <bluescreen_avenger@verzion.net>
#
#    This file is (going to be) part of RebeccaBlackOS.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

###########################################################################################
#
#PARSE DESKTOP ENTRIES
#PARSE DESKTOP ENTRIES
DesktopFileData=$(awk 'BEGIN{filenum+=1} {print $0 "#" filenum} \
ENDFILE {print "[Desktop Entry]#" filenum; \
print "PhysicalFileName=" FILENAME "#" filenum; \
print "Enabled=#" filenum; \
print "Name=#" filenum; \
print "Comment=#" filenum; \
print "Type=#" filenum; \
print "IsFallbackSession=#" filenum; \
print "CompositorDisplayArgument=#" filenum; \
print "CompositorSeatArgument=#" filenum; \
print "SessionArgument=#" filenum; \
print "AdditionalArguments=#" filenum; \
print "CompositorExec=#" filenum; \
print "EnvironmentFile=#" filenum; \
print "EOF=#" filenum; \
filenum+=1}' \
Desktop/rebeccablacklinux/rebeccablackos_files/usr/share/wsessions.d/*.desktop | awk '/\[Desktop Entry]/{flag=1;next}/\[/{flag=0}flag' )



DesktopFileDataList=$(echo "$DesktopFileData" | sed -e 's/[0-9][0-9][0-9]#//g' -e 's/^ *Enabled *= */000#/' \
-e 's/^ *Name *= */001#/' \
-e 's/^ *Comment *= */002#/' \
-e 's/^ *Type *= */003#/' \
-e 's/^ *IsFallbackSession *= */004#/' \
-e 's/^ *CompositorDisplayArgument *= */005#/' \
-e 's/^ *CompositorSeatArgument *= */006#/' \
-e 's/^ *SessionArgument *= */007#/' \
-e 's/^ *AdditionalArguments *= */008#/' \
-e 's/^ *CompositorExec *= */009#/' \
-e 's/^ *EnvironmentFile *= */010#/' \
-e 's/^ *PhysicalFileName *= */011#/' \
-e 's/^ *EOF *= */012#/' \
-e "/^[0-9][0-9][0-9]#/!d" | sort -t "#" -nk 3,3 -k1,1 -u | sed -e 's/#[[:digit:]]\+$//g' -e 's/012#/\r/g' )


DesktopFileDataList=${DesktopFileDataList//$'\n'$'\r'$'\n'/$'\r'}
IFS=$'\r'
DesktopFileDataArray=(${DesktopFileDataList//$'\n'$'\r'/})
unset IFS

unset DesktopFileDataList
#
###########################################################################################



###########################################################################################
#
#Get NeedsFiles
NeedsFilesList=$(echo "$DesktopFileData" | sed -e 's/[0-9][0-9][0-9]#//g' \
-e 's/^ *NeedsFile *= */000#/' \
-e 's/^ *EOF *= */001#/' \
-e "/[0-9][0-9][0-9]#/!d" | perl -pe 's/\$(\w+)/$ENV{$1}/g' | sort -t "#" -k 3,3 -k 1,1 | sed -e 's/#[[:digit:]]\+$//g' -e 's/001#/\r/g')

IFS=$'\r'
NeedsFilesArray=($NeedsFilesList)
unset IFS

#
###########################################################################################

###########################################################################################
#
#Get Seat HW support
DesktopFileCount=${#DesktopFileDataArray[@]}

DesktopFileBackendArrayPlaceholders=""
for (( iterator=1 ; iterator <= $DesktopFileCount ; iterator++ ))
do
  for BACKEND in KMS WL FB
  do
    BackendPlaceHolders=""
    BackendPlaceHolders+=$'\n'"CompositorSupports${BACKEND}=#$iterator"
    BackendPlaceHolders+=$'\n'"Compositor${BACKEND}Arguments=#$iterator"
    BackendPlaceHolders+=$'\n'"Compositor${BACKEND}SeatAware=#$iterator"
    BackendPlaceHolders+=$'\n'"Compositor${BACKEND}SeatArgument=#$iterator"
    DesktopFileBackendArrayPlaceholders+=$'\n'$BackendPlaceHolders$'\n'
  done
done

SeatHardwareList=$(echo "$DesktopFileData"$'\n'"$DesktopFileBackendArrayPlaceholders" | sed  -e 's/[0-9][0-9][0-9]#//g' \
-re "s/^ *CompositorSupports(KMS|WL|FB) *= */000#000#\1#/" \
-re  "s/^ *Compositor(KMS|WL|FB)Arguments *= */000#001#\1#/" \
-re  "s/^ *Compositor(KMS|WL|FB)SeatAware *= */000#002#\1#/" \
-re  "s/^ *Compositor(KMS|WL|FB)SeatArgument *= */000#003#\1#/" \
-e 's/^ *EOF *= */001#999#999#/' \
-e "/^[0-9][0-9][0-9]#/!d" | sed -re 's/^([0-9][0-9][0-9]#[0-9][0-9][0-9])#KMS#/\1#100#/g' \
-re 's/^([0-9][0-9][0-9]#[0-9][0-9][0-9])#WL#/\1#101#/g' \
-re 's/^([0-9][0-9][0-9]#[0-9][0-9][0-9])#FB#/\1#102#/g' | sort -t "#"  -k5,5 -k1,1 -u -k3,3 -k2,2 | sed -re 's/^([0-9][0-9][0-9]#[0-9][0-9][0-9])#100#/\1#KMS#/g' \
-re 's/^([0-9][0-9][0-9]#[0-9][0-9][0-9])#101#/\1#WL#/g' \
-re 's/^([0-9][0-9][0-9]#[0-9][0-9][0-9])#102#/\1#FB#/g' | sed -e 's/#[[:digit:]]\+$//g' -e 's/001#999#999#/\r/g')

IFS=$'\r'
SeatHardwareArray=($SeatHardwareList)
unset IFS

#
########################################################################################### 
